trigger:
- master

pool:
  name: 'my-personal-computer'  # Make sure this matches the exact name of your personal agent pool

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
